language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-confit' ]; then cd .. && eval "mv $currentfolder generator-confit" && cd generator-confit; fi
