sudo: false
language: node_js
node_js:
  - 6

# Need to specify a GCC compiler now!
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
env:
  # Create a build matrix from the available test files
  - CXX=g++-4.8 TEST_SUITE_M_OF_N=1-5
  - CXX=g++-4.8 TEST_SUITE_M_OF_N=2-5
  - CXX=g++-4.8 TEST_SUITE_M_OF_N=3-5
  - CXX=g++-4.8 TEST_SUITE_M_OF_N=4-5
  - CXX=g++-4.8 TEST_SUITE_M_OF_N=5-5

matrix:
  fast-finish: true     # https://docs.travis-ci.com/user/customizing-the-build/#Fast-Finishing

addons:
  firefox: "45.0"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  # Installing Yarn - https://yarnpkg.com/en/docs/install-ci#travis-tab
  # Repo for newer Node.js versions
  #- curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  #- npm install -g yarn

  # Install NPM 3.9.5
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3.9.5; fi
  - npm prune
  - npm set progress=false

install:
  - npm install -g yo
  - npm install
  - npm link
#  - yarn global add yo
#  - yarn install
#  - yarn link

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

script:
  - npm run pre-release

after_success:
  - npm run upload-coverage
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

notifications:
  email:
    recipients:
      - u_glow@hotmail.com

cache:
  directories:
  - $HOME/.yarn-cache
