sudo: false
language: node_js
node_js:
  - "5.11.0"
  - "6.2"

# Need to specify a GCC compiler now!
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
env:
  # Create a build matrix from the available test files
  - CXX=g++-4.8 TEST_SUITE_CHUNKS=5 TEST_SUITE=1
  - CXX=g++-4.8 TEST_SUITE_CHUNKS=5 TEST_SUITE=2
  - CXX=g++-4.8 TEST_SUITE_CHUNKS=5 TEST_SUITE=3
  - CXX=g++-4.8 TEST_SUITE_CHUNKS=5 TEST_SUITE=4
  - CXX=g++-4.8 TEST_SUITE_CHUNKS=5 TEST_SUITE=5

matrix:
  fast-finish: true     # https://docs.travis-ci.com/user/customizing-the-build/#Fast-Finishing

addons:
  firefox: "45.0"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm prune
  - npm set progress=false

install:
  - npm install --quiet -g yo
  - npm install --quiet
  - npm link

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

script:
  - npm test

after_success:
  - npm run semantic-release

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

notifications:
  email:
    recipients:
      - u_glow@hotmail.com

